### ISSUE TITLE
Seed for consistency

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/Smokescreen#45]
If we ensure that a given seed always results in the same set of cosmological parameters, it can be used to blind different probes individually. This will remove the necessity of generating the data vectors of all your probes at the same time.

IMPORTANT reminder: save the seed on the blinded data vector file!

**Comment by arthurmloureiro** [comment]
# To Do

- [ ] Add seed as a metadata to the saved sacc
- [ ] Include more metadata to the sacc file
- [ ] copy the original metadata to the sacc file
- [ ] test if the same seed yields the same shifts in different computers.

**Comment by arthurmloureiro** [comment]
I realised I was not keeping the original metadata in the blinded sacc!

This is now fixed :) 

I also added a `concealed = True` metadata  !

**Comment by arthurmloureiro** [comment]
## `seed = "test"`
Locally:  `Shifts: {'Omega_c': 0.25876948503900465, 'sigma8': 0.7726193034315977}`
Sunrise:

**Comment by arthurmloureiro** [comment]
I also tested that if you give different number of parameters, the values are the same for the same parameters:
- Locally (omega_c and sigma8): `Shifts: {'Omega_c': 0.21229098052498757, 'sigma8': 0.7142436174585977}`
- Sunrise (only omega_c): `Shifts: {'Omega_c': 0.21229098052498757}`

**Comment by arthurmloureiro** [comment]
Now, of course... if you invert or change the order of the required shift parameters, the shifts will be different:
- Locally: `Shifts: {'sigma8': 0.7001923251481939, 'Omega_c': 0.22084394106175506}`
- Sunrise (inverted order): `Shifts: {'Omega_c': 0.21229098052498757, 'sigma8': 0.7142436174585977}`

Maybe this can be avoided by looping over CCL dictionaries of cosmological parameters instead of looping over the shifts dictionary...

**Comment by arthurmloureiro** [comment]
> Now, of course... if you invert or change the order of the required shift parameters, the shifts will be different:
> 
> * Locally: `Shifts: {'sigma8': 0.7001923251481939, 'Omega_c': 0.22084394106175506}`
> * Sunrise (inverted order): `Shifts: {'Omega_c': 0.21229098052498757, 'sigma8': 0.7142436174585977}`
> 
> Maybe this can be avoided by looping over CCL dictionaries of cosmological parameters instead of looping over the shifts dictionary...

yeah, that worked!
