### ISSUE TITLE
Publish Smokescreen on conda-forge

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/Smokescreen#56]
No clue how to do this... my plan is to follow [this tutorial](https://www.pyopensci.org/python-package-guide/tutorials/publish-conda-forge.html)

@stuartmcalpine do you have a tutorial to recommend?

**Comment by beckermr** [comment]
See here: https://github.com/conda-forge/staged-recipes/pull/27198

**Comment by arthurmloureiro** [comment]
oh brilliant @beckermr !

Tagging @stuartmcalpine here too!

So one thing I did not fully understand yet is how to explain in the recipe some dependencies that only exist in conda-forge and not on pip like firecrown and cosmosis-standard-lib... but it seems like the recipe doesn't even need to know that...

**Comment by beckermr** [comment]
So conda-forge is totally separate from pypi. The things listed in the recipe are for the conda-forge packages that install the python software you need.

**Comment by beckermr** [comment]
This is done! Closing!

**Comment by arthurmloureiro** [comment]
@beckermr should I be able to `conda install -c conda-forge smokescreen` ?
Or does it take some time?

**Comment by beckermr** [comment]
use this

`conda install -c conda-forge lsstdesc-smokescreen`
